# The socket addresses that the workers listen on.
# They are read by the dispatcher and the workers in order to connect to each other.
workers = [
    "172.31.5.37:5000",
    "172.31.3.62:6000",
    "172.31.11.22:7000",
    "172.31.0.10:8000",
    "172.31.2.148:9000"
]
# Dispatcher does not listen on any port, but we need to know its IP address.
# This is because our workers only accept connections from known IP addresses,
# so that traffic from the internet cannot disrupt our workers.
dispatcher = "172.31.5.110"